feat(database setup):database setup
atlp-rwanda/alpha-ec-be pull request #22
Opened 2024-04-03 16:17 UTC by IRASUBIZA-Elyse

fixing database setup

[#187300130]

2024-04-03 16:19 UTC, Ruthuwamahoro reviewed
Great job

2024-04-03 16:19 UTC, Ruthuwamahoro approved these changes

2024-04-03 19:15 UTC, Mukunzijames approved these changes

2024-04-04 07:15 UTC, TuyishimireEric approved these changes

2024-04-04 08:10 UTC, fab-ryan requested changes
good work but I need good structured PR Description, rebase and change then of `merge_request_template.md` to `pull_request_template.md`

2024-04-04 13:10 UTC, fab-ryan approved these changes

2024-04-04 13:10 UTC, merged