feat(Product CRUD): CRUD operation of product
atlp-rwanda/alpha-ec-be pull request #24
Opened 2024-04-04 17:07 UTC by TuyishimireEric

### issue in referencing?

### Questions:

#### What does this PR do?

CRUD operation of a product
#### Description of Task to be completed?

the user should be able to add/create items for sale
Such that the stock can be seen by any requesting client

#### How should this be manually tested?

- run `npm install` 
- run `npm run migrate`
- run `npm run seed`
- run `npm run dev`
- check the [swagger documentation ](http://localhost:3000/swagger/)

#### Any background context you want to provide?

-dummy data are provided before having the real data

#### What are the relevant pivotal tracker/Trello stories?

- id of the project #187300155

#### Questions:

2024-04-08 14:49 UTC, fab-ryan commented on src/controllers/productController.ts
> +      slug: name.split(' ').join('-'),
create separate function it's will better in looking and check if the name has special characteres  ignore them

2024-04-08 14:51 UTC, fab-ryan commented on src/database/models/index.ts
> +  });
add this in each model it's will be readable

2024-04-08 14:54 UTC, fab-ryan commented on src/helper/buildQuery.ts
it's seems this file is for only product while we can use it in different getting or update request try to make it resuable by any modal

2024-04-08 14:55 UTC, fab-ryan commented on src/helper/excOperation.ts
this is one is good

2024-04-08 14:56 UTC, fab-ryan requested changes
also add pagination helper function

2024-04-08 17:03 UTC, fab-ryan commented on src/database/models/index.ts
> +  });
please work on this

2024-04-08 18:25 UTC, TuyishimireEric commented on src/helper/excOperation.ts
Thank you

2024-04-09 03:28 UTC, Mukunzijames approved these changes

2024-04-09 06:40 UTC, Ruthuwamahoro approved these changes

2024-04-09 10:33 UTC, fab-ryan approved these changes
good work

2024-04-09 11:57 UTC, merged