Ft update profile 187300152
atlp-rwanda/alpha-ec-be pull request #25
Opened 2024-04-04 20:54 UTC by RWEMAREMY

### issue in referencing?

### Questions:

#### What does this PR do?

Update the user profile

#### Description of Task to be completed?
the user should be able to edit the profile

#### How should this be manually tested?

- run `npm run dev`
- check the [swagger documentation ](http://localhost:3000/swagger/)

#### Any background context you want to provide?

-dummy data are provided before having the real data

#### What are the relevant pivotal tracker/Trello stories?

- id of the project #187300152

#### Questions:

2024-04-09 09:40 UTC, fab-ryan requested changes
Please rebase first

2024-04-09 15:10 UTC, fab-ryan commented on .gitignore
> +>>>>>>> ee1cd9c (feat(update-profile):user updating profile)
rebase

2024-04-09 15:12 UTC, fab-ryan commented on src/config/passportConfig.ts
> +      const user = await Database.User.findOne({
const {id} = jwtPayload

2024-04-09 15:14 UTC, fab-ryan commented on src/validations/userValidation.ts
> +  image: Joi.string().optional(),
remove this

2024-04-09 15:14 UTC, fab-ryan commented on src/validations/userValidation.ts
> +  gender: Joi.string().optional(),
enum here

2024-04-09 15:15 UTC, fab-ryan commented on src/validations/userValidation.ts
> +    .regex(/^(?:\+?\d{12}|\d{10})$/)
078,079,072,073, validate use this

2024-04-09 15:16 UTC, fab-ryan commented on src/database/migrations/20240325172706-create-user.js
> +      },
remove this create migration files

2024-04-09 15:16 UTC, fab-ryan commented on src/database/migrations/20240325172706-create-user.js
> +      },
also this remove those

2024-04-09 15:22 UTC, fab-ryan requested changes
wark on those reviews

2024-04-10 14:11 UTC, fab-ryan requested changes
first rebase and squash the commits

2024-04-11 12:34 UTC, istafrica-dennw commented on src/config/config.js
> -    host: process.env[`${prefix}_HOST`] || '5432',
@manzidavidrw why did you change the database port ?

2024-04-11 12:47 UTC, manzidavidrw commented on src/config/config.js
> -    host: process.env[`${prefix}_HOST`] || '5432',
that's the port we all have

2024-04-12 13:23 UTC, fab-ryan requested changes
Correct that image

2024-04-12 13:23 UTC, fab-ryan commented on src/database/migrations/20240325172706-update-profile.js
> +    await queryInterface.addColumn('users', 'image', {
Please we have profileUrl use that

2024-04-12 13:23 UTC, fab-ryan commented on src/database/migrations/20240325172706-update-profile.js
> +    await queryInterface.removeColumn('users', 'image');
Remove this because it's was already implemented

2024-04-12 13:23 UTC, fab-ryan commented on src/database/models/user.ts
> +  image: string;
Remove image use profileUrl

2024-04-12 13:23 UTC, fab-ryan commented on src/database/models/user.ts
> +      image: this.image,
And this

2024-04-12 14:04 UTC, fab-ryan commented on package.json
> -    "sinon-chai": "^3.7.0",
why replacing this chai

2024-04-14 21:23 UTC, fab-ryan commented on src/utils/pagination.ts
> +  const currentPage = pageNumber ? +pageNumber : 0;
you have changed this seection why please don't

2024-04-14 21:23 UTC, fab-ryan commented on src/validations/userValidation.ts
> +  birthdate: Joi.string().optional(),
please validate this date

2024-04-14 21:24 UTC, fab-ryan requested changes
I need to know the test coverage, status and work on those comments

2024-04-15 03:01 UTC, RWEMAREMY commented on src/validations/userValidation.ts
> +  birthdate: Joi.string().optional(),
yes

2024-04-15 04:26 UTC, RWEMAREMY commented
coverage 99%

2024-04-15 11:49 UTC, Ruthuwamahoro approved these changes

2024-04-15 11:51 UTC, Sophie20202 approved these changes

2024-04-15 11:54 UTC, Ruthuwamahoro approved these changes

2024-04-15 11:55 UTC, Sophie20202 approved these changes

2024-04-15 12:11 UTC, Nadinefiona approved these changes

2024-04-15 12:34 UTC, fab-ryan approved these changes
Good work

2024-04-15 12:34 UTC, merged