Ft admin set role #187300154
atlp-rwanda/alpha-ec-be pull request #27
Opened 2024-04-05 03:32 UTC by Mukunzijames

issue in referencing?

Questions:

What does this PR do?

setting role and permission

• setting role for users [admin,seller,buyer]
.creating role 
.assing role to someone

What are the relevant pivotal tracker/Trello stories?
• id of the project
#187300154

2024-04-09 06:41 UTC, Ruthuwamahoro approved these changes

2024-04-09 15:33 UTC, fab-ryan commented on src/database/migrations/20240325172706-create-user.js
> +      roleId: {
separate file

2024-04-09 15:48 UTC, fab-ryan commented on src/controllers/roleController.ts
> +      },
use trim function

2024-04-09 15:51 UTC, fab-ryan commented on src/swagger.json
> +      "url": "http://localhost:5000",
please be consistance

2024-04-09 15:51 UTC, fab-ryan requested changes
work on those comments

2024-04-09 19:10 UTC, Nadinefiona approved these changes

2024-04-10 18:25 UTC, fab-ryan approved these changes

2024-04-10 18:29 UTC, merged