login-via-google
atlp-rwanda/alpha-ec-be pull request #29
Opened 2024-04-05 11:05 UTC by Nadinefiona

#### What does this PR do?

This PR implements the functionality for users to log in to the app using their Google accounts. 

#### Description of Task to be completed?

This task involves adding Google login functionality to the app's backend, enhancing user experience and security. It includes documenting the feature with Swagger, developing an algorithm for Google OAuth integration, updating the user model, creating API endpoints, and ensuring at least 80% test coverage. 

#### How should this be manually tested?

1. npm run install
2. npm run dev
3. then swagger for testing 

#### Any background context you want to provide?

This feature enhances the app's user experience by providing a convenient way for users to log in using their Google accounts, streamlining the registration and login process. It also leverages Google's security infrastructure to protect user credentials.

#### What are the relevant pivotal tracker/Trello stories?

-Story ID: 123456789

2024-04-10 14:04 UTC, fab-ryan commented on src/database/migrations/20240325172706-create-user.js
> +      },
please create new migration

2024-04-10 14:06 UTC, fab-ryan requested changes
please follow eveyrthing and you are storing content that are not needed like profile what's the meaning of profile

2024-04-11 08:07 UTC, fab-ryan commented on src/database/migrations/20240410162214-add-auth-table.js
> +      verified: {
why creating new table we are already have user table

2024-04-11 08:07 UTC, fab-ryan commented on src/database/models/auth.ts
> +  declare address: string;
this is useless file we have user model

2024-04-11 08:08 UTC, fab-ryan commented on src/routers/index.ts
>  router.use('/api', routers);
please follow the structure of current codes

2024-04-11 08:09 UTC, fab-ryan requested changes
Please don't create new file for user why team are not communicating

2024-04-11 12:54 UTC, fab-ryan commented on src/app.ts
> +app.use(session({ secret: 'scrt', resave: false, saveUninitialized: true }));
please use create team defined in config file

2024-04-11 12:54 UTC, fab-ryan commented on src/app.ts
> +
can you clarify why did you use session??

2024-04-11 12:59 UTC, fab-ryan commented on src/routers/authRoute.ts
> +router.get('/users/google', authController.initiateGoogleLogin);
if you say /google what it mean at least can be google-auth or login-google but you must follow what you have written in docs, precisely that endpoint understoondable

2024-04-11 13:01 UTC, fab-ryan requested changes
-  ***first the naming of commit is not following the instruction we can't know if it's feature , chore, or bug***

- work on those comments
- squash those commits

2024-04-11 14:36 UTC, fab-ryan commented on src/controllers/authController.ts
> +        return res.status(500).json({ error: 'Failed to generate token' });
please remove userObject we don't need it

2024-04-11 14:37 UTC, fab-ryan requested changes
squash those commits to one or two

2024-04-12 07:30 UTC, Mukunzijames approved these changes

2024-04-12 07:58 UTC, fab-ryan approved these changes

2024-04-12 08:00 UTC, merged