feat(restPassword):forgot password
atlp-rwanda/alpha-ec-be pull request #34
Opened 2024-04-14 19:48 UTC by IRASUBIZA-Elyse

### Questions:

#### What does this PR do?

resetting password via email

#### Description of Task to be completed?

- send a forgot password request
- reset the password via eamil using the link sent to the email

#### How should this be manually tested?

- valid the email used to reset password
- use the link sent to the email and reset the password

#### What are the relevant pivotal tracker/Trello stories?

- id of the project
 #187300149

#### Questions:

2024-04-14 20:12 UTC, Nadinefiona approved these changes

2024-04-19 14:42 UTC, fab-ryan commented on src/controllers/resetPasswordController.ts
> +import bcrypt from 'bcrypt';
we are using brcyptjs not this

2024-04-19 14:43 UTC, fab-ryan commented on src/controllers/resetPasswordController.ts
> +    );
we already have token generator function

2024-04-19 14:44 UTC, fab-ryan commented on src/controllers/resetPasswordController.ts
> +    };
and also this

2024-04-19 14:45 UTC, fab-ryan commented on src/routers/userRoute.ts
> +router.post('/users/forgot-password', forgotPassword);
validation of email is required

2024-04-19 14:46 UTC, fab-ryan commented on src/utils/sendEmails.ts
> +export default sendResetPasswordEmail;
this whole function of sending email is build already please first ready the code before starting implementations

2024-04-19 14:47 UTC, fab-ryan commented on src/validations/userValidation.ts
> +      return value;
avoid using this method please use regix methods

2024-04-19 14:48 UTC, fab-ryan requested changes
I have remained with comments

2024-04-23 21:15 UTC, musabehonore approved these changes

2024-04-24 03:19 UTC, Mukunzijames approved these changes

2024-04-25 07:30 UTC, fab-ryan commented on src/controllers/resetPasswordController.ts
> +      data,
you shouldn't have set data to cookies
and also should be token not data

2024-04-25 07:32 UTC, fab-ryan requested changes
Please change that lines

2024-04-25 12:29 UTC, fab-ryan approved these changes

2024-04-25 12:30 UTC, merged