fix(Product CRUD): CRUD operation of product
atlp-rwanda/alpha-ec-be pull request #35
Opened 2024-04-15 14:42 UTC by TuyishimireEric

### issue in referencing?

### Questions:

#### What does this PR do?

CRUD operation of a product
#### Description of Task to be completed?

the user should be able to add/create items for sale
Such that the stock can be seen by any requesting client

#### How should this be manually tested?

- run `npm install` 
- run `npm run migrate`
- run `npm run seed`
- run `npm run dev`
- check the [swagger documentation ](http://localhost:3000/swagger/)

#### Any background context you want to provide?

-dummy data are provided before having the real data

#### What are the relevant pivotal tracker/Trello stories?

- id of the project #187300155

#### Questions:

2024-04-15 14:50 UTC, fab-ryan commented on src/database/migrations/20240414205718-create-category.js
> +        type: Sequelize.DATE,
add status of category

2024-04-16 08:03 UTC, Nadinefiona approved these changes

2024-04-16 08:59 UTC, fab-ryan commented on src/config/config.js
> +  const env = process.env.NODE_ENV || 'production';
please use development by default

2024-04-16 09:00 UTC, fab-ryan commented on src/controllers/categoryController.ts
> +import { CategoryAttributes } from '../database/models/category';
you are missing update

2024-04-16 09:06 UTC, fab-ryan requested changes
work to those comments

2024-04-16 09:07 UTC, TuyishimireEric commented on src/config/config.js
> +  const env = process.env.NODE_ENV || 'production';
I have changed thanks

2024-04-16 09:08 UTC, TuyishimireEric commented on src/controllers/categoryController.ts
> +import { CategoryAttributes } from '../database/models/category';
Let me add it too

2024-04-16 10:20 UTC, fab-ryan approved these changes

2024-04-16 12:32 UTC, musabehonore approved these changes

2024-04-16 12:32 UTC, Mukunzijames approved these changes

2024-04-16 12:36 UTC, merged