Ft cart 187300163
atlp-rwanda/alpha-ec-be pull request #41
Opened 2024-04-18 09:32 UTC by RWEMAREMY

**What does this PR do?**
This PR implements the functionality of Cart for Buyer 

**Description of Task to be completed?**
This task involves adding Cart functionality and listing all products at the app's backend,

**How should this be manually tested?**
Run npm install to install all dependencies.
Start the development server with npm run dev.
Use swagger for testing
Any background context you want to provide?
This feature enhances the app's user experience by providing a convenient and effective usability to utelize Cart  through purchasing various product. 

**What are the relevant pivotal tracker/Trello stories?**
Story ID:[#187300163]

2024-04-21 22:05 UTC, fab-ryan commented on tsconfig.json
> +    "src/database/models/cart.js"
why this file??

2024-04-21 22:06 UTC, fab-ryan requested changes
work on those also

2024-04-24 13:25 UTC, fab-ryan commented on src/controllers/cartsController.ts
> +        404,
if product is exist it's doesn't mean it's 404 no we must have special status code

2024-04-24 13:27 UTC, fab-ryan commented on src/controllers/cartsController.ts
> +      return sendResponse<null>(res, 404, null, 'Quantity Exceeds Stock');
if it's exceed it's should be [like](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406)

2024-04-24 13:27 UTC, fab-ryan commented on src/controllers/cartsController.ts
> +      return sendResponse(res, 200, cart, 'Product added to cart');
if we create we use 201

2024-04-24 13:31 UTC, fab-ryan requested changes
status code must be changed

2024-04-24 14:46 UTC, fab-ryan requested changes
First figured out why your test are not passing

2024-04-26 15:08 UTC, Mukunzijames approved these changes

2024-04-26 16:32 UTC, musabehonore approved these changes

2024-04-27 00:21 UTC, Nadinefiona approved these changes

2024-04-27 07:54 UTC, TuyishimireEric approved these changes

2024-04-27 18:18 UTC, fab-ryan approved these changes

2024-04-27 18:19 UTC, merged