#187300153 Admin Account Disable and Activate
atlp-rwanda/alpha-ec-be pull request #43
Opened 2024-04-19 00:41 UTC by musabehonore

# What does this PR do?
This PR implements the functionality for Admin to disable and activate any user account on the app.

# Description of Task to be completed?
An admin will be able to disable and activate any user's account and send them an email explaining the reasons for the suspension.
# How should this be manually tested?
### For testing only
npm install
npm run test
### For running the app
npm run install
npm run demigrate
npm run migrate
npm run seed
npm run dev

# Any background context you want to provide?
No background feature added.

# What are the relevant pivotal tracker/Trello stories?
-Story ID: #187300153

2024-04-21 21:50 UTC, fab-ryan commented on src/controllers/loginController.ts
> +    if (user.status !== 'Active') {
please use boolean not a string

2024-04-21 21:53 UTC, fab-ryan commented on src/controllers/userStatusController.ts
> +    if (user.status === statuses[action]) {
you don't need actions can be vice versa true or false

2024-04-21 21:55 UTC, fab-ryan commented on src/database/migrations/20240411085039-add_auth_columns_to_users.js
> +      defaultValue: 'Active',
please if you have new task that require to add new column please create it's own migration

2024-04-21 21:56 UTC, fab-ryan requested changes
work on those commets

2024-04-23 07:41 UTC, fab-ryan commented on src/routers/userRoute.ts
> +router.post('/users/:id/accountStatus', isAuthenticated, isAdmin, userStatus);
we have naming conversation of api like if verifyEmail should be verify-email or account-status

2024-04-23 07:42 UTC, fab-ryan requested changes
change that endpoint naming

2024-04-23 13:41 UTC, Mukunzijames approved these changes

2024-04-23 14:25 UTC, Sophie20202 approved these changes

2024-04-23 14:33 UTC, fab-ryan approved these changes

2024-04-23 14:34 UTC, merged