Ft wishlist 187300161
atlp-rwanda/alpha-ec-be pull request #46
Opened 2024-04-20 18:20 UTC by Mukunzijames

What does this PR do?

this PR for wishlist functionality: Added feature to view, add, and delete items. Enhanced user experience with seamless management of wishlisted items, ensuring smoother navigation and interaction.

Description of Task to be completed?
The task involves the following key functionalities:

- Validate that the buyer is logged in.
- Add the item to the buyer's wishlist.
- Retrieve the product details from the database.
- Store the updated wishlist in the buyer's account.
- Return a confirmation message to the frontend."

What are the relevant pivotal tracker stories?
Story ID:#187300161

2024-04-22 08:46 UTC, fab-ryan requested changes
work on those comments

2024-04-22 08:46 UTC, fab-ryan commented on src/controllers/wishlistController.ts
> +      const productIds = products.map(product => product.id);
you can get only ids using select commands

2024-04-22 08:46 UTC, fab-ryan commented on src/controllers/wishlistController.ts
> +        include: [{ model: Database.Product, as: 'product' }],
make as products not product

2024-04-22 08:46 UTC, fab-ryan commented on src/database/models/wishlist.ts
> +      productId: this.productId,
the product will even be returned?

2024-04-22 08:46 UTC, fab-ryan commented on src/middleware/authentication.ts
> +    return sendResponse(res, 403, null, 'Not authorized! User should be admin');
only the Not authorized is enuogh donn't specify the role

2024-04-22 08:49 UTC, musabehonore approved these changes

2024-04-23 08:28 UTC, Nadinefiona approved these changes

2024-04-23 11:10 UTC, fab-ryan approved these changes
good work

2024-04-23 11:10 UTC, merged