Ft chat application 187300175
atlp-rwanda/alpha-ec-be pull request #48
Opened 2024-04-23 13:11 UTC by Ruthuwamahoro

### issue in referencing?

### Questions:

#### What does this PR do?

-creation of chat application

#### Description of Task to be completed?

- Allow only authenticated people to use our chat application
- Sent message in real time application
- Storing all messages in database

#### How should this be manually tested?

- set up the env according to your localhost database credentials
- use the api in the index.ts in routers to connect to the database
- run npm run install to install the necessary dependencies
- use npm run dev to connect to the database

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

- Acceptance Criteria

GIVEN the user is online
WHEN they open the chat tab
THEN they should be able to read all of the past chats

GIVEN the user is online
WHEN they open the chat tab
THEN they should be able to post a public chat

GIVENthe user
WHEN they post a chat
THEN it should be able to be echoed to all online users in realtime.

- id of the project
  #187300175

#### Questions: Not applicable

2024-04-23 13:20 UTC, fab-ryan requested changes
work on that only

2024-04-23 13:30 UTC, Ruthuwamahoro commented on package.json
> +    "mysql2": "^3.9.4",
solved

2024-04-23 13:39 UTC, Mukunzijames commented on package.json
> +    "mysql2": "^3.9.4",
also squash commit you have 4 commits

2024-04-23 13:39 UTC, Mukunzijames approved these changes

2024-04-23 13:47 UTC, fab-ryan commented on src/server.ts
> +});
wrap this into single function then call that function here

2024-04-23 13:49 UTC, fab-ryan requested changes
wrapping the functionality of sockets

2024-04-24 12:02 UTC, fab-ryan approved these changes

2024-04-24 13:07 UTC, RWEMAREMY approved these changes
good job

2024-04-24 13:08 UTC, Nadinefiona approved these changes
Good Work 👏

2024-04-24 13:18 UTC, merged