Ft testing mocha 187303859
atlp-rwanda/alpha-ec-be pull request #5
Opened 2024-03-28 15:54 UTC by RWEMAREMY

2024-03-28 16:08 UTC, musabehonore approved these changes
I think this fantastic

2024-03-28 16:18 UTC, Mukunzijames approved these changes

2024-03-29 04:16 UTC, RWEMAREMY reviewed
done

2024-03-29 04:59 UTC, TuyishimireEric commented on src/config/config.js
> +        database: process.env.TEST_DATABASE_NAME ?? "",
Please resolve these errors, you may replace this line `database: process.env.TEST_DATABASE_NAME ?? "",` to `database: process.env.TEST_DATABASE_NAME ?? '',`

2024-03-29 05:14 UTC, TuyishimireEric commented on src/config/config.js
> +        password: process.env.TEST_DATABASE_PASSWORD ?? "",
Please `Rebase` to update your branch and resolve these **linter errors**, 🙏

2024-03-29 05:28 UTC, TuyishimireEric commented on src/config/config.js
> +        password: process.env.TEST_DATABASE_PASSWORD ?? "",
> Please `Rebase` to update your branch and resolve these **linter errors**, 🙏
> 
> **Steps Perform the Rebase**
> 
> 1. Checkout to the `develop` branch
> 2. Pull the updates from GitHub by running `git pull`
> 3. Checkout to your feature branch
> 4. start git rebase with `git rebase develop`
> 5. resolve the conflicts
> 6. continue to rebase with `git add .` and then `git rebase --continue`
> 7. save the changes
> 
> These steps will update your **feature branch**, you have to run `npm i` to update `node_modules`, please run `npm run lint:fix` and make sure that all **linter errors are fixed**
> 
> test your codes, 👍

After performing these steps the errors will be resolved

2024-03-29 05:49 UTC, fab-ryan commented on .nyc_output/processinfo/1d54fa34-f1f2-4c75-ac34-f17f9f74021a.json
> +{"parent":null,"pid":14836,"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\REMY\\Desktop\\ANDELA\\alpha-ec-be\\node_modules\\mocha\\bin\\mocha.js","--require","ts-node/register","test/serve
Please put this in gitignore

2024-03-29 05:49 UTC, fab-ryan commented on .nyc_output/processinfo/index.json
> +{"processes":{"1d54fa34-f1f2-4c75-ac34-f17f9f74021a":{"parent":null,"children":[]}},"files":{"C:\\Users\\REMY\\Desktop\\ANDELA\\alpha-ec-be\\src\\app.ts":["1d54fa34-f1f2-4c75-ac34-f17f9f74021a"],"C:\
same as here

2024-03-29 05:51 UTC, fab-ryan commented on coverage/lcov-report/base.css
> +h2 { font-size: 14px; }
a very output of test must be in gitignore

2024-03-29 05:54 UTC, fab-ryan commented on src/app.ts
> +
why this export app???

2024-03-29 05:54 UTC, fab-ryan commented on src/config/config.js
> +        database: process.env.TEST_DATABASE_NAME ?? "",
Please work on this comment

2024-03-29 05:55 UTC, fab-ryan commented on src/config/config.js
> +
why the addition of those line you didn't rebase

2024-03-29 05:56 UTC, fab-ryan commented on src/controllers/demo.ts
why creating this file we have our controller

2024-03-29 05:56 UTC, fab-ryan commented on src/controllers/dummyController.ts
> +}
Please don't change someone else codes

2024-03-29 05:57 UTC, fab-ryan commented on src/routers/dummyRoute.ts
same as here

2024-03-29 05:58 UTC, fab-ryan requested changes
Please work on comment @TuyishimireEric  and I asked you

2024-03-29 09:39 UTC, closed without merging