Ft Listing Related product and  seller information
atlp-rwanda/alpha-ec-be pull request #51
Opened 2024-05-01 23:03 UTC by Sophie20202

**What does this PR do?**

This is Listing related product specifically for buyers.

**Description of Task to be completed?**

This task will require A product Id in order to retrieve all its related products

**How should this be manually tested?**

This will be tested by using Get a single product with  Id

**What are the relevant pivotal tracker/Trello stories?**
id of the project
#187505367

2024-05-02 10:41 UTC, fab-ryan requested changes
why did you remove all products
- related product must be based on single not all products
- also create different endpoint to make it better understanding
- your have remove the current code which was about search and filter product

2024-05-03 13:18 UTC, Sophie20202 commented
Already resolved

2024-05-03 13:59 UTC, fab-ryan commented on src/controllers/productController.ts
> +        where: {
response {
product,
relatedproduct,
seller info
}

2024-05-03 14:00 UTC, fab-ryan requested changes
seller info not include but remain don't pass out the password

2024-05-06 06:46 UTC, fab-ryan commented on src/controllers/productController.ts
> +    });
here you will return also this product meaning not related

2024-05-06 06:46 UTC, fab-ryan commented on src/controllers/productController.ts
> +        limit: 4,
and also here this is not related

2024-05-06 06:49 UTC, fab-ryan requested changes
You need to come up your own algorithm for resolving

2024-05-06 07:26 UTC, fab-ryan commented on src/controllers/productController.ts
> +    });
no algorithm there

2024-05-06 07:27 UTC, fab-ryan requested changes
you didn't provide algorithm for related

2024-05-06 11:54 UTC, fab-ryan approved these changes

2024-05-06 12:03 UTC, musabehonore approved these changes

2024-05-06 12:03 UTC, RWEMAREMY approved these changes
good job

2024-05-06 12:11 UTC, manzidavidrw approved these changes

2024-05-06 13:23 UTC, Mukunzijames approved these changes

2024-05-06 14:16 UTC, merged