feat(updating password):allow user to update password at any amount o…
atlp-rwanda/alpha-ec-be pull request #54
Opened 2024-05-03 14:29 UTC by Ruthuwamahoro

### issue in referencing?

### Questions:

#### What does this PR do?

Change password at x amount of time 

#### Description of Task to be completed?

- Sending a message to the email to update the password before the expiration date
- If the Notification is neglected and the date exceeds the expired date,he/she is prompted to reset the password

#### How should this be manually tested?

- set up the env according to your localhost database credentials
- use the api in the index.ts in routers to connect to the database
- use npm run dev to connect to the database

#### Any background context you want to provide?

-dummy data are provided before having the real data

#### What are the relevant pivotal tracker/Trello stories?

- id of the project
  #187300173

#### Questions:

2024-05-06 07:00 UTC, fab-ryan commented on src/controllers/loginController.ts
> +        if (user.roleId !== 'd290f1ee-6c54-4b01-90e6-d701748f0853') {
don't use id use name please

2024-05-06 07:01 UTC, fab-ryan commented on src/controllers/passwordExpirationcron.ts
> +      },
again use name

2024-05-06 07:16 UTC, fab-ryan commented on src/middleware/authentication.ts
> +          if (user.roleId !== 'd290f1ee-6c54-4b01-90e6-d701748f0853') {
don't use id

2024-05-06 07:18 UTC, fab-ryan requested changes
change that don't use id

2024-05-06 12:46 UTC, musabehonore approved these changes

2024-05-07 05:35 UTC, Ruthuwamahoro commented on src/middleware/authentication.ts
> +          if (user.roleId !== 'd290f1ee-6c54-4b01-90e6-d701748f0853') {
done

2024-05-07 05:35 UTC, Ruthuwamahoro commented on src/controllers/passwordExpirationcron.ts
> +      },
done

2024-05-07 05:35 UTC, Ruthuwamahoro commented on src/controllers/loginController.ts
> +        if (user.roleId !== 'd290f1ee-6c54-4b01-90e6-d701748f0853') {
solved

2024-05-07 10:29 UTC, Nadinefiona approved these changes

2024-05-07 11:05 UTC, fab-ryan approved these changes

2024-05-07 14:38 UTC, merged