feat(working on notification)
atlp-rwanda/alpha-ec-be pull request #71
Opened 2024-06-20 15:46 UTC by Ruthuwamahoro

### Questions:

#### What does this PR do?

-Resolving conflicts between chat app and notification

#### Description of Task to be completed?

-Ensure that chat app and chat share the same server
-ensure that chat app is working correctly
-Ensure that the notification app is working

#### How should this be manually tested?

- set up the env according to your localhost database credentials
- use the api in the index.ts in routers to connect to the database
- use npm run dev to connect to the database

#### Any background context you want to provide?

-dummy data are provided before having the real data

2024-07-08 09:00 UTC, musabehonore approved these changes

2024-07-08 09:03 UTC, Sophie20202 approved these changes

2024-07-08 09:08 UTC, RWEMAREMY approved these changes
Good

2024-07-08 14:54 UTC, fab-ryan commented on public/index.html
> +          const socket = io('http://localhost:3000/', {
change this please

2024-07-08 14:54 UTC, fab-ryan commented on public/index.html
> +            const messages = await fetch('http://localhost:3000/api/chats', {
same as here

2024-07-08 14:55 UTC, fab-ryan requested changes
Please remove that hard coded url

2024-07-09 11:34 UTC, fab-ryan approved these changes

2024-07-09 11:34 UTC, merged

2024-07-09 11:34 UTC, Ruthuwamahoro commented
> Please remove that hard coded url

done